[package]
name = "rummikub"
version = "0.1.0"
edition = "2021"

[dependencies]
time-graph = { version = "0.3.1", features = ["table"] }

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html